export const CATEGORIES_ACTION_TYPES = {
  FETCH_CATEGORIES_START: "category/FETCH_CATEGORIES_START",
  FETCH_CATEGORIES_START_SUCCESS: "category/FETCH_CATEGORIES_START_SUCCESS",
  FETCH_CATEGORIES_START_FAIL: "category/FETCH_CATEGORIES_START_FAIL",
};
